### ISSUE TITLE
logFile path is set to a local file 

### ISSUE THREAD

**Issue by shishirprakash** [satzkumr/YarnApplicationAnalyzer#1]
under bin/appanalyzer.sh log file path is hard coated change it to $2

also , what is the use of setting ANALYZER_HOME and sourcing  $ANALYZER_HOME/etc/analyzerEnv.sh ?

**Comment by satzkumr** [comment]
Code change committed for comment#1, 
For "ANALYZER_HOME and sourcing $ANALYZER_HOME/etc/analyzerEnv.sh ?", this is added simply for now as a plan of isolating the code runtime config separately in future.

**Comment by satzkumr** [comment]
#issue closed
